SUSE/clang-extract

- libcextract/ArgvParser.cpp
- libcextract/ArgvParser.hh
- libcextract/FunctionDepsFinder.hh
- libcextract/HeaderGenerate.cpp
- libcextract/HeaderGenerate.hh
- libcextract/Passes.cpp
- libcextract/Passes.hh
- libcextract/meson.build
This commit adds a way for clang-extract to generate a header file containing forward declarations of all functions.
This can be enabled by using -DCE_OUTPUT_FUNCTION_PROTOTYPE_HEADER=<arg>. The generated file is not self-compilable.
@marcosps Please review and check if this is the intended behavior.
> Add new option to create a header with foward declaration of all functions

- libcextract/FunctionDepsFinder.cpp
- testsuite/small/record-4.c
There are some cases where a variable is declared as follows:
```
static const struct mount_opts
{
int token;
int mount_opts;
int flags;
} ext4_mount_opts[] = {
{1, 1, 1}
};
```
in this case, the `ext4_mount_opts` array is declared together with its type, thus resulting in Clang splitting this into two decls in its AST:
```
struct mount_opts
{
int token;
int mount_opts;
int flags;
};
static const struct ext4_mount_opts[] = {
{1, 1, 1}
};
```
but since we try to get what the user wrote, it results in two declarations of `struct mount_opts`, thus clang-extract fails because of a redeclaration error. But since `ext4_mount_opts` is an array, geting its type returns an array type, not the struct declaration itself, hence check for this case as well.
> Fix redeclaration of RecordDecl in Records defined in array variables

- libcextract/ArgvParser.cpp
Since clang-extract removes the static keyword from the extracted function, and kernel can enable -Werror, avoid the procedure to stop because of missing prototype.
> libcextract: ArgvParser: Add -Wno-missing-prototypes

- libcextract/SymbolExternalizer.cpp
- testsuite/small/rename-16.c
Previously, FunctionUpdater::Update_References_To_Symbol skipped the variable initializer because DeclaratorDecl::getBody fails to retrieve the initialization Expr once it expects the object to be a function. This commit fixes this by explicitely checking for a VarDecl and getting its initializer.
> Fix `Update_References_To_Symbol` skipping variable initializer

- libcextract/SymbolExternalizer.cpp
- testsuite/small/macro-20.c
When sweeping through macros for identifier we must also use '.' in the tokenizer to correctly get accesses to structs in macro parameters. This commit addresses that.
> Set '.' as a delimiter to the macro tokenizer

- libcextract/PrettyPrint.cpp
- testsuite/small/record-5.c
Previously, clang-extract dropped __attribute__(()) after the definition of a RecordDecl. This could possibly generate wrong code if the __attribute__ is relevant for code layout, for example.
@marcosps Please check if it fixes the wrong code on TOMOYO.
Closes #13
> Fix potentially wrong code by dropping attributes after RecordDecls

- libcextract/ArgvParser.cpp
> ArgvParser: Remove -fmin-function-alignment=16 argument

- .github/workflows/testsuite.yml
- libcextract/DscFileGenerator.cpp
- libcextract/FunctionDepsFinder.cpp
- libcextract/LLVMMisc.cpp
- libcextract/LLVMMisc.hh
- libcextract/PrettyPrint.cpp
- testsuite/meson.build
- testsuite/small/attr-7.c
- testsuite/small/closure-3.c
clang has a mechanism (DeclContext::lookup) which is **SUPPOSED TO** return the list of all Decls that matches the lookup name.  However, this method doesn't work as intented.  In kernel (see github issue #20) it results in the lookup_result set not having the Decl that has the body of the function, which is the most important!
Therefore, we fallback to the older but slower method: sweep through the AST top level looking for the Decls we want to extract.
If this issue in the symbol name hash comes from a bug in LLVM, this still needs investigation.
> FunctionDepsFinder: Fix closure computation not analyzing functions which have a prototype declared after its body

- contrib/suse-install-llvm.sh
- libcextract/SymbolExternalizer.cpp
- libcextract/SymbolExternalizer.hh
- testsuite/lib/runtest.py
- testsuite/small/rename-17.c
Previously, the SymbolExternalizer did not run on TypeOfTypeExpr, causing constructions such as
```
typeof(symbol_to_externalize) x;
```
to fail compilation because `symbol_to_externalize` was renamed to something else.  Fix this by hacking a RecursiveASTVisitor that parses all types in the function and update the reference.
Fixes #24
> Fix SymbolExternalizer skipping symbols in typeof()

- libcextract/IntervalTree.hh
- libcextract/SymbolExternalizer.cpp
- libcextract/SymbolExternalizer.hh
Previously, we had a double nested for to check for intersections, which requires n(n-1)/2 comparions. This commit introduces a red-black IntervalTree, which can reduce it down to O(n log n).
> Use IntervalTree to speed-up the SymbolExternalizer

- libcextract/SymbolExternalizer.cpp
- libcextract/SymbolExternalizer.hh
Deltas were designed to replace text, not inserting text.  This may be a source of bugs, so we only register the change we did into the FileEntryMap and pass the change directly to clang's Rewriter.
> Avoid using Deltas to insert text

- libcextract/Passes.cpp
- libcextract/SymbolExternalizer.cpp
- libcextract/SymbolExternalizer.hh
Some kernel versions do not support IBT.  Check if we have such cases and emit a runtime error if found.
> Check generated code for IBT compatibilty

- libcextract/ArgvParser.cpp
This can be happen on older codestreams, so don't bother erroring out in those cases.
> ArgvParser: Disable incompatible-pointer-types-discard-qualifiers

- libcextract/FunctionDepsFinder.cpp
- libcextract/FunctionDepsFinder.hh
- testsuite/linux/typedef-1.c
> FunctionDepsFinder: Check for declarations inside another declaration

- testsuite/linux/ibt-2.c
We don't include this file anymore, now we output the KLP_RELOC_SYMBOL macro instead. The test is now passing.
> testsuite: linux: ibt-2: Do not check for livepatch.h

- libcextract/SymbolExternalizer.cpp
- testsuite/ccp/ext-obj-5.c
Extend current ccp test to catch a regression found.
> SymbolExternalizer: Use visitor to get the array size expression

- libcextract/FunctionDepsFinder.cpp
- libcextract/FunctionDepsFinder.hh
This change reduced the time to finishe running clang-extract from ~13 seconds to ~9 seconds in a specific use symbol being extracted.
> FunctionDepsFinder: Improve performance of duplicated typedef removal

- README.md
LLVM16 generates wrong C attributes, and this was fixed on LLVM18. Update the dependency install command to suggest people to use LLVM18 instead.
> README.md: Update deps install to use LLVM18

- libcextract/SymbolExternalizer.cpp
- testsuite/linux/ibt-typeof-1.c
When constructing the TypeUpdateVisitor we should OR with Ibt so it does not wrap the use of the symbol with (*s).
> Fix SymbolExternalizer wrapping when IBT is enabled

- testsuite/small/attr-1.c
- testsuite/small/attr-6.c
ppc64le uses a different register to get the current stack pointer.
> testsuite: attr: Adapt testcase to be executed on ppc64le

- libcextract/Passes.cpp
- libcextract/PrettyPrint.cpp
- libcextract/PrettyPrint.hh
- testsuite/small/attr-8.c
- testsuite/small/attr-9.c
Undefine noinline macro if conflicts with AST dump
In kernel sourcecode there is a definition of a macro:
```
#define noinline __attribute__((noinline))
```
This seems harmless, but when clang-extract decides to dump the AST of
a Decl, this conflicts with its attr:
```
__attribute__((noinline))
```
which results in the resulting code being broken. Hence, undefine this
macro for the AST dump and define it later.
Closes #15
Signed-off-by: Giuliano Belinassi <gbelinassi@suse.de>
> Noinline fix

- meson.build
libLLVM provided on openSUSE leap are built with gcc-7 headers, which is results in crashes if clang-extract is build with any gcc headers other than 7. Hence we make sure to pass the system's gcc headers to clang so everything works as expected.
> Add logic to get the system's gcc headers install folder

- .github/workflows/testsuite.yml
There are no SUSE products using llvm-16, hence drop it in favor of llvm-17 and llvm-18.
Note that this does not drop support for llvm-16. However, this is a step towards that, as supporting it may not interest no one.
> Github CI: Drop llvm-16, enable llvm-17 and 18

- libcextract/PrettyPrint.cpp
- testsuite/small/attr-10.c
Some typedef definitions have attributes that are applied to the TagDecl it defines to. For example:
```
typedef union {
struct sockaddr *__restrict __sockaddr__;
} __SOCKADDR_ARG __attribute__((__transparent_union__));
```
Here, __attribute__((__transparent_union__)) is applied to the union, not the typedef. Hence we also need to search for the TagDecl (the union in this case) for the extra attributes.
Closes #68
> Check the TagDecl in TypedefNameDecl for extra attributes

- libcextract/Closure.cpp
- libcextract/Closure.hh
- libcextract/FunctionDepsFinder.cpp
- libcextract/FunctionDepsFinder.hh
- libcextract/Passes.cpp
- libcextract/SymbolExternalizer.cpp
- libcextract/SymbolExternalizer.hh
- libcextract/meson.build
- testsuite/lateext/lateext-6.c
Instead of externalizing to the first use, externalize now to the first effective use, that means the first decl that won't be discarded by the closure.
> Implement Late externalization to the first effective use

- libcextract/LLVMMisc.cpp
- libcextract/LLVMMisc.hh
- libcextract/PrettyPrint.cpp
- libcextract/PrettyPrint.hh
- libcextract/SymbolExternalizer.cpp
- testsuite/lateext/location-1.c
- testsuite/lateext/location-1.h
When a variable is externalized through LateExternalization, we also have to carry the comment location of the OldDecl to the NewDecl once we are not replacing the text in the same SourceRange the OldDecl was. This commit fixes this by inserting this comment on the text of the NewDecl.
> Fix location comment of LateExternalized variables

- libcextract/Closure.hh
- libcextract/PrettyPrint.cpp
- testsuite/small/attr-11.c
- testsuite/small/vectortype-1.c
Clang handle __attribute__((__vector_size__((N)))) attributes differently from the general case.  While other attributes resides in the AttrVec structure, those are hardcoded in the VectorType structure and the AttrVec may contain nothing.  Hence we also need to trigger the Get_Expanded_Loc for this case as well even if we can't get the SourceLocation of this attribute.
Closes #68 (I hope for the last time! :) )
> Fix dropped attributes from vector types

- libcextract/Closure.hh
- testsuite/small/record-nested-3.c
When clang detects that a certain struct doesn't need a full definition, i.e. its size is not required, then the flag CompleteDefinitionRequired is set to false.  But in the following case:
```
struct Fts3Table {
struct Fts3Index {
int nPrefix;
} *aIndex;
};
int fts3PrefixParameter(
const char *zParam,
int *pnIndex,
struct Fts3Index **apIndex
){
int a = sizeof(struct Fts3Index);
return 0;
}
```
this results in the nested struct `Fts3Index` not being output as its parent struct `Fts3Table` is marked as CompleteDefinitionRequired as false.  In such cases we have to force CompleteDefinitionRequired of the parent struct as true so that its inner structs can be output.
Fix #77
> Fix nested struct being discarded if parent struct is flagged as partial

- libcextract/Closure.hh
- libcextract/LLVMMisc.cpp
- libcextract/LLVMMisc.hh
- testsuite/small/attr-13.c
- testsuite/small/typedef-14.c
- testsuite/small/typedef-15.c
- testsuite/small/typedef-16.c
There are some types in which we lose the the typedef reference, for example:
typedef void (*XtErrorHandler)(char *);
extern void XtSetErrorHandler(XtErrorHandler __attribute((noreturn)));
The type dump for this is:
```
FunctionProtoType 0x5210000720e0 'void (void (*)(char *) __attribute__((noreturn)))' cdecl
|-BuiltinType 0x521000014170 'void'
`-PointerType 0x521000071fd0 'void (*)(char *) __attribute__((noreturn))'
`-ParenType 0x521000071f70 'void (char *) __attribute__((noreturn))' sugar
`-FunctionProtoType 0x521000071f30 'void (char *) __attribute__((noreturn))' noreturn cdecl
|-BuiltinType 0x521000014170 'void'
`-PointerType 0x521000014d10 'char *'
`-BuiltinType 0x5210000141b0 'char'
```
Notice that there is no reference for XtErrorHandler.  Somehow clang was not able to identify …
> Fix closure missing TypedefDecl because not being referenced by type

- libcextract/Closure.cpp
- libcextract/Closure.hh
- libcextract/FunctionDepsFinder.cpp
- libcextract/LLVMMisc.cpp
- libcextract/LLVMMisc.hh
- libcextract/NonLLVMMisc.hh
- testsuite/small/enum-10.c
- testsuite/small/typedef-15.c
- testsuite/small/typedef-16.c
Analyze Decls with same BeginLoc
This commit fixes the following cases:
```
extern void
GetMagickMemoryMethods(AcquireMemoryHandler *,ResizeMemoryHandler *, DestroyMemoryHandler *),
*ResetMagickMemory(void *,int,const size_t);
void f()
{
(void) ResetMagickMemory((void*)0,0,0);
}
```
Before this patch, the generated code would fail because
AcquireMemoryHandler, ResizeMemoryHandler and DestroyMemoryHandler
would not be dragged into the closure.
@5c4lar : can you check if this commit fixes your issues?
Closes #94 #95
> Closure fixes

- libcextract/InlineAnalysis.cpp
- libcextract/Passes.cpp
- libcextract/SymbolExternalizer.hh
- testsuite/linux/Modules.symvers
- testsuite/linux/weak-symbols.c
Until this point all symbols found in kernel mode (usually using Symvers file), were strong (with externalized variables) or none (which copied the symbols to the closure). Now clang-extract checks is the symbol is present on vmlinux, meaning that the symbol is weak externalized, meaning the the symbol will be always present.
> libcextract: Add support for Weak symbols for kernel mode

- libcextract/Passes.cpp
- testsuite/includes/pch-1.c
- testsuite/includes/pch-1.h
Clang provides a feature to speedup header parsing which consists of generating a PrecompiledHeader (.pch) file to avoid having to compile the header multiple times if the main file needs to be reparsed multiple times, which is the case we are interested.
However, there seems to be a bug there because the Preprocessor is re-instantiated after generating them, loosing the __COUNT__ counter value. So we disable it until this issue is fixed.
After testing PCH enabled vs. disabled, I noticed clang-extract is significantly *faster* if PCH is disabled, hence disable it once for all (1.6s vs. 1.0s for vmwgfx_execbuf case).
Closes #8
> Disable Precompiled Headers

- libcextract/ArgvParser.cpp
This happens on recent kernel tree due to issues with LLVM. As we don't need any backends and only need to parse the source code we can disable the warning and move on.
For more information about the issue take a look into https://github.com/ClangBuiltLinux/linux/issues/2013 and https://github.com/llvm/llvm-project/issues/93449.
> libcextract: ArgvParser: Disable Wduplicate-decl-specifier error

- libcextract/Closure.cpp
- libcextract/Closure.hh
- testsuite/small/record-nested-5.c
On the following example:
```
struct ll {
union {
unsigned long key;
void *key_ptr;
};
struct ll *next;
};
```
Even if we don't need the full definition of `ll` it is dragged into the output because when analyzing this `union` field it tries to go up and set `struct ll` as having its body necessary once there was no way for it to know that it went there as a consequence of adding `struct ll` to the closure, rather than it being there because of a foward union declaration inside a struct.  This commit fixes this by pushing the Decls into a stack as a way to know which declarations we are currently analyzing.
> Fix CompleteDefinition of struct being dragged into output because of union fields

- libcextract/PrettyPrint.cpp
- testsuite/small/attr-14.c
Workarounds this bizarre corner case found in iwlwifi kernel module.
Closes #115
> Workaround ';' being output at incorrect location when decl ends with `#endif`

- libcextract/FunctionDepsFinder.cpp
- libcextract/LLVMMisc.cpp
- libcextract/LLVMMisc.hh
- testsuite/small/redundant-1.c
Pass through the closure set looking for Decls we can erase. For example:
```
struct ll;
struct ll;
int get(struct ll *);
struct ll;
```
We just need the first `struct ll;`
> Remove redundant decls

- libcextract/ExpansionPolicy.cpp
This is now working, so it's safer to rely on relative paths for kernel extraction.
> libcextract: ExpansionPolicy.cpp: use relative path

- libcextract/LLVMMisc.cpp
- libcextract/LLVMMisc.hh
- libcextract/SymbolExternalizer.cpp
- testsuite/lateext/lateext-7.c
- testsuite/lateext/lateext-7.h
In the case where a variable is declared as a consequence of a macro expansion, as an example:
```
#include "lateext-7.h"
DEFINE_STATIC_KEY_FALSE(aaa);
```
What happens is that when trying to get the FileID of `aaa` it returns the FileID for the include file rather than the main file.  Hence make sure it gets the expansion location rather than the spelling location.
Closes #118
> Fix Late Externalization when variable is declared as macro expansion

- libcextract/ArgvParser.cpp
std::filename is not present on clang17, so it's easier to use basename so we are covered.
> libcextract: ArgvParser: Use basename instead of std::filename

- libcextract/ArgvParser.cpp
- libcextract/ArgvParser.hh
- libcextract/ElfCXX.cpp
- libcextract/ElfCXX.hh
- libcextract/InlineAnalysis.cpp
- libcextract/InlineAnalysis.hh
- libcextract/Passes.hh
- libcextract/SymbolExternalizer.cpp
- testsuite/ccp/ext-obj-5.c
- testsuite/includes/rewrite-1.c
- testsuite/includes/rewrite-2.c
- testsuite/includes/rewrite-4.c
- testsuite/inline/inlined-into-1.c
- testsuite/lateext/lateext-2.c
- testsuite/lateext/lateext-3.c
- testsuite/lateext/lateext-4.c
- testsuite/lateext/lateext-5.c
- testsuite/lateext/lateext-6.c
- testsuite/lateext/lateext-7.c
- testsuite/lateext/location-1.c
- testsuite/small/rename-10.c
- testsuite/small/rename-12.c
- testsuite/small/rename-15.c
- testsuite/small/rename-2.c
- testsuite/small/rename-3.c
- testsuite/small/rename-4.c
- testsuite/small/rename-5.c
- testsuite/small/rename-6.c
- testsuite/small/rename-8.c
- testsuite/small/rename-9.c
This PR contains multiple fixes with regard to symbol externalization for what concerns Userspace Livepathing. As follows:
- Every strong externalized function/variable now contains the attribute `used` to avoid gcc to remove the variable read on assembly (i.e. inlining the pointer to always be `NULL`). This most likely also affects kernel livepatching and possibly it went unnoticed so far because of the gcc version they are currently using. [Here is an example of this happening for function `f`, while `g` is correct](https://godbolt.org/z/9vYTvvz14).
- Fix symbol visibility if it is only available on `.symtab` section. `dlsym` won't be able to find such symbols, hence they should be strongly externalized rather than weakly.
- Allow clang-extract to be feed with two DEBUGINFO files: one …
> Fix externalization on Userpsace Livepatching

- libcextract/Passes.cpp
This was changed on linux kernel mailing list due to possible problems on binutils. For more information take a look here[1];
[1]: https://lore.kernel.org/all/ZljceDZ7eqEJtYhQ@redhat.com/
> libcextract: Passes: Adjust KLP_RELOC_SYMBOL_POS format

- libcextract/SymbolExternalizer.cpp
Otherwise it doesn't recognize the following expression:
if (unlikely(!check_prev_ino(leaf, key, slot, prev_key)))
Closes: #129
> SymbolExternalizer: Add ! to TOKEN_VECTOR

- README.md
- libcextract/ASTUnitHack.cpp
- libcextract/ArgvParser.cpp
- libcextract/ArgvParser.hh
- libcextract/Passes.cpp
- libcextract/Passes.hh
- libcextract/meson.build
- testsuite/small/ignore-errors.c
Sometime it is useful to not halt compilation if an error occurred because the generated code may still be useful when creating livepatches.  Hence add a new option:
```
-DCE_IGNORE_CLANG_ERRORS
```
To ignore clang errors and continue compilation even so.
> Allow clang-extract to ignore errors pointed by clang

- .github/workflows/testsuite.yml
- libcextract/IncludeTree.cpp
- libcextract/MacroWalker.cpp
- libcextract/PrettyPrint.cpp
- libcextract/SymbolExternalizer.cpp
- libcextract/SymbolExternalizer.hh
- testsuite/ccp/ext-obj-5.c
- testsuite/includes/rewrite-1.c
- testsuite/includes/rewrite-2.c
- testsuite/includes/rewrite-4.c
- testsuite/lateext/lateext-2.c
- testsuite/lateext/lateext-3.c
- testsuite/lateext/lateext-4.c
- testsuite/lateext/lateext-5.c
- testsuite/lateext/lateext-6.c
- testsuite/lateext/lateext-7.c
- testsuite/lateext/location-1.c
- testsuite/small/rename-10.c
- testsuite/small/rename-12.c
- testsuite/small/rename-15.c
- testsuite/small/rename-2.c
- testsuite/small/rename-3.c
- testsuite/small/rename-4.c
- testsuite/small/rename-5.c
- testsuite/small/rename-6.c
- testsuite/small/rename-8.c
- testsuite/small/rename-9.c
This commit updates the codebase so that it compiles with llvm-19.
- Replaces uses of FileEntry::getName() with FileEntryRef::getName().
- Update the __attribute__((used)) location on the tests.
> Add support to llvm-19

- .github/workflows/testsuite.yml
- libcextract/ClangCompat.hh
- libcextract/Passes.cpp
The function `CompilerInstance::createDiagnostics()` changed its signature in llvm-20, hence we need to check the llvm version and adjust the call properly.
This also adds llvm-20 to the CI.
> Add compatibility to llvm-20

- libcextract/LLVMMisc.cpp
Fixes the following build error on 32bit systems:
```
[12:53:45] libcextract/LLVMMisc.cpp: In function ‘llvm::ArrayRef<clang::Decl*> Get_Toplev_Decls_With_Same_Beginloc(clang::ASTUnit*, const clang::SourceLocation&)’:
[12:53:45] libcextract/LLVMMisc.cpp:236:39: error: call of overloaded ‘ArrayRef(std::nullptr_t, long unsigned int)’ is ambiguous
[12:53:45]   236 |   return ArrayRef<Decl *>(nullptr, 0UL);
[12:53:45]       |                                       ^
[12:53:45] In file included from /opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/local/include/llvm/Support/Format.h:25,
[12:53:45]                  from /opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/local/include/llvm/Support/Error.h:24,
[12:53:45]                  from …
```
> Fix ArrayRef constructor ambiguity on 32-bit systems

- README.md
- libcextract/ArgvParser.cpp
- libcextract/ExpansionPolicy.cpp
- libcextract/ExpansionPolicy.hh
- testsuite/includes/policy-compiler-1.c
- testsuite/includes/policy-system-1.c
This commit add two new expansion policies:
- system: keep includes from system headers, such as stdio.h, stdlib.h, and other libraries that may be installed in the system.
- compiler: keep compiler-specific includes, such as stdatomic.h, stddef.h, and other includes that may expand into compiler-specific code.
Use `-DCE_KEEP_INCLUDES=<policy>` to use them.
Closes #139
> Add new expansion policies.
